services:
  sakila-db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-sakila-db-data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d

volumes:
  mysql-sakila-db-data: